# Generated by Django 3.2.9 on 2022-02-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
