# Generated by Django 3.2.9 on 2022-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
