# Generated by Django 3.2.9 on 2022-04-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='nickname',
            new_name='callsign',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='picture',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
