# Generated by Django 3.2.9 on 2022-02-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='favoriteIds',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='joinedDate',
        ),
    ]
