# Generated by Django 3.2.9 on 2022-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
        ('accounts', '0004_useraccount_joineddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favoriteIds',
            field=models.ManyToManyField(blank=True, null=True, to='tasker.Task'),
        ),
    ]
