# Generated by Django 3.2.9 on 2022-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_favoriteids'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
