# Generated by Django 3.2.9 on 2021-12-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('algorithms', 'algorithms'), ('dataStructure', 'dataStructure'), ('architecture', 'architecture'), ('basics', 'basics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(blank=True, max_length=160, unique=True),
        ),
    ]
