# Generated by Django 3.2.9 on 2022-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20220227_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.CharField(choices=[('cplusplus', 'cplusplus'), ('c', 'c'), ('csharp', 'csharp'), ('javascript', 'javascript'), ('python', 'python')], max_length=50, null=True),
        ),
    ]
