# Generated by Django 3.2.9 on 2021-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20211223_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
