# Generated by Django 3.2.9 on 2021-12-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_alter_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('CSharp', 'CSharp'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java')], max_length=50, null=True),
        ),
    ]
